//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan MainWindowGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["MainWindowGlobalTime"]));
            }
            set {
                this["MainWindowGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan ActsReaderGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["ActsReaderGlobalTime"]));
            }
            set {
                this["ActsReaderGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan CharactersGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["CharactersGlobalTime"]));
            }
            set {
                this["CharactersGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan FactionsViewGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["FactionsViewGlobalTime"]));
            }
            set {
                this["FactionsViewGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan LocationViewGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["LocationViewGlobalTime"]));
            }
            set {
                this["LocationViewGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan CollectablesMapsGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["CollectablesMapsGlobalTime"]));
            }
            set {
                this["CollectablesMapsGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan MusicPlayerGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["MusicPlayerGlobalTime"]));
            }
            set {
                this["MusicPlayerGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan DatesGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["DatesGlobalTime"]));
            }
            set {
                this["DatesGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan MiniGamesGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["MiniGamesGlobalTime"]));
            }
            set {
                this["MiniGamesGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan MissionsGlobalTime {
            get {
                return ((global::System.TimeSpan)(this["MissionsGlobalTime"]));
            }
            set {
                this["MissionsGlobalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isMusicPlaying {
            get {
                return ((bool)(this["isMusicPlaying"]));
            }
            set {
                this["isMusicPlaying"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSSplaying {
            get {
                return ((bool)(this["isSSplaying"]));
            }
            set {
                this["isSSplaying"] = value;
            }
        }
    }
}
